# Generated by Django 4.2.7 on 2023-12-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_follows_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='folowed',
            new_name='followed',
        ),
    ]
