# Generated by Django 4.2.7 on 2023-12-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_follow_following_alter_follow_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
    ]
